### ISSUE TITLE
[account_invoice_line_pricelist] V8 [bug] Name field is overwritten on save invoice line

### ISSUE THREAD

**Issue by alyngsoe** [onesteinbv/addons-onestein#41] opened 2017-12-06 09:32 UTC
To reproduce the bug:
On invoice lines
1. Enter product ( product.name is fetched to invoiceline name field)
2. Change the value of the name field 
3. Change one or more of the values (Quantity, price, analytic)
4. Save the line (ENTER)
Result: The name filed on the line is overridden by the product.name.

Screenshot attached:
![croppercapture 11](https://user-images.githubusercontent.com/12607073/33654443-6e12e254-da70-11e7-8ab2-33596a5cc2f3.jpg)

**Comment by espo-tony** [comment] 2018-02-20 13:18
Hi @alyngsoe ,
I committed a change to the module account_invoice_line_pricelist which should solve the issue you signaled. Can I ask you, please, to check if the issue is solved?

**Closed as completed** 2018-03-20 13:04 UTC
